/**
 * Mock Mistral provider for testing
 * Implements Mistral-specific behavior and response formats
 */

import { vi } from 'vitest';
import { createMockProvider, MockResponseBuilder } from './base.mock.js';
import { ProviderError, ErrorCodes } from '../../../src/providers/interface.js';

// Mistral model configurations matching the real provider
const MISTRAL_MODELS = {
  'mistral-large-latest': {
    modelName: 'mistral-large-latest',
    friendlyName: 'Mistral Large',
    contextWindow: 128000,
    maxOutputTokens: 128000,
    supportsStreaming: true,
    supportsImages: false,
    supportsTemperature: true,
    supportsWebSearch: false,
    supportsThinking: false,
    timeout: 60000,
    description: 'Top-tier reasoning model for complex tasks',
    aliases: ['mistral-large-2411'],
  },
  'mistral-small-latest': {
    modelName: 'mistral-small-latest',
    friendlyName: 'Mistral Small',
    contextWindow: 128000,
    maxOutputTokens: 128000,
    supportsStreaming: true,
    supportsImages: false,
    supportsTemperature: true,
    supportsWebSearch: false,
    supportsThinking: false,
    timeout: 30000,
    description: 'Cost-efficient reasoning model for low-latency workloads',
    aliases: ['mistral-small-2409'],
  },
  'codestral-latest': {
    modelName: 'codestral-latest',
    friendlyName: 'Codestral',
    contextWindow: 32768,
    maxOutputTokens: 32768,
    supportsStreaming: true,
    supportsImages: false,
    supportsTemperature: true,
    supportsWebSearch: false,
    supportsThinking: false,
    timeout: 60000,
    description: 'Code generation model',
    aliases: ['codestral-2405'],
  },
  'ministral-8b-latest': {
    modelName: 'ministral-8b-latest',
    friendlyName: 'Ministral 8B',
    contextWindow: 128000,
    maxOutputTokens: 128000,
    supportsStreaming: true,
    supportsImages: false,
    supportsTemperature: true,
    supportsWebSearch: false,
    supportsThinking: false,
    timeout: 30000,
    description: 'Lightweight model for edge deployment',
    aliases: ['ministral-8b-2410'],
  },
  'pixtral-large-latest': {
    modelName: 'pixtral-large-latest',
    friendlyName: 'Pixtral Large',
    contextWindow: 128000,
    maxOutputTokens: 128000,
    supportsStreaming: true,
    supportsImages: true,
    supportsTemperature: true,
    supportsWebSearch: false,
    supportsThinking: false,
    timeout: 60000,
    description: 'Multimodal model for image understanding',
    aliases: ['pixtral-large-2411'],
  },
};

// Create Mistral-specific mock provider
export function createMockMistralProvider(overrides = {}) {
  return createMockProvider({
    name: 'mistral',

    getSupportedModels: vi.fn().mockImplementation(() => MISTRAL_MODELS),

    getModelConfig: vi.fn().mockImplementation((modelName) => {
      // Check direct match
      if (MISTRAL_MODELS[modelName]) {
        return MISTRAL_MODELS[modelName];
      }

      // Check aliases
      for (const model of Object.values(MISTRAL_MODELS)) {
        if (model.aliases && model.aliases.includes(modelName)) {
          return model;
        }
      }

      return null;
    }),

    invoke: vi.fn().mockImplementation(async (messages, options = {}) => {
      const modelConfig =
        MISTRAL_MODELS[options.model] || MISTRAL_MODELS['mistral-large-latest'];

      // Simulate Mistral-specific validations
      if (!options.config?.apiKeys?.mistral) {
        throw new ProviderError(
          'Mistral API key is required',
          ErrorCodes.MISSING_API_KEY,
        );
      }

      // Simulate image handling for vision models
      const hasImages = messages.some(
        (msg) =>
          Array.isArray(msg.content) &&
          msg.content.some((item) => item.type === 'image'),
      );

      if (hasImages && !modelConfig.supportsImages) {
        throw new ProviderError(
          `Model ${options.model} does not support images`,
          ErrorCodes.INVALID_REQUEST,
        );
      }

      // Simulate code generation for Codestral
      if (modelConfig.modelName.includes('codestral')) {
        return new MockResponseBuilder()
          .withContent(
            '```python\ndef mock_function():\n    return "Generated by Codestral"\n```',
          )
          .withModel(options.model)
          .withProvider('mistral')
          .build();
      }

      // Default response
      return new MockResponseBuilder()
        .withContent('Mock Mistral response')
        .withModel(options.model || 'mistral-large-latest')
        .withProvider('mistral')
        .build();
    }),

    ...overrides,
  });
}

// Export default instance
export const mockMistralProvider = createMockMistralProvider();

// Mock response generators for Mistral format
export function createMockMistralResponse(
  content = 'Test response',
  options = {},
) {
  return {
    id: `mistral-${Date.now()}`,
    object: 'chat.completion',
    created: Math.floor(Date.now() / 1000),
    model: options.model || 'mistral-large-latest',
    choices: [
      {
        index: 0,
        message: {
          role: 'assistant',
          content,
          tool_calls: null,
        },
        finish_reason: options.finish_reason || 'stop',
        logprobs: null,
      },
    ],
    usage: {
      prompt_tokens: options.prompt_tokens || 10,
      completion_tokens: options.completion_tokens || 20,
      total_tokens:
        (options.prompt_tokens || 10) + (options.completion_tokens || 20),
    },
  };
}

// Mock streaming response generator
export function createMockMistralStreamResponse(
  chunks = ['Hello', ' world', '!'],
  options = {},
) {
  const streamId = `mistral-${Date.now()}`;

  return chunks.map((chunk, index) => ({
    id: streamId,
    object: 'chat.completion.chunk',
    created: Math.floor(Date.now() / 1000),
    model: options.model || 'mistral-large-latest',
    choices: [
      {
        index: 0,
        delta: {
          content: chunk,
          role: index === 0 ? 'assistant' : undefined,
        },
        finish_reason: index === chunks.length - 1 ? 'stop' : null,
        logprobs: null,
      },
    ],
    usage:
      index === chunks.length - 1
        ? {
          prompt_tokens: options.prompt_tokens || 10,
          completion_tokens: options.completion_tokens || 20,
          total_tokens:
              (options.prompt_tokens || 10) + (options.completion_tokens || 20),
        }
        : null,
  }));
}

// Error response generators
export function createMockMistralError(
  type = 'invalid_api_key',
  message = null,
) {
  const errors = {
    invalid_api_key: {
      message: message || 'Unauthorized',
      type: 'invalid_api_key',
      code: 'unauthorized',
    },
    rate_limit: {
      message: message || 'Rate limit exceeded',
      type: 'rate_limit_error',
      code: 'rate_limit_exceeded',
    },
    model_not_found: {
      message: message || 'Model not found',
      type: 'invalid_request_error',
      code: 'model_not_found',
    },
    context_length: {
      message: message || 'Context length exceeded',
      type: 'invalid_request_error',
      code: 'context_length_exceeded',
    },
  };

  return {
    error: errors[type] || errors.invalid_api_key,
  };
}

// Create a mock Mistral client with configurable behavior
export function createMockMistralClient(behavior = {}) {
  return {
    chat: {
      complete: vi.fn().mockImplementation(async (params) => {
        if (behavior.throwError) {
          const error = new Error('Mistral API error');
          error.response = {
            status: behavior.errorCode || 400,
            data: createMockMistralError(behavior.errorType),
          };
          throw error;
        }

        if (params.stream) {
          const chunks = behavior.chunks || ['Test', ' streaming', ' response'];
          const streamData = createMockMistralStreamResponse(chunks, {
            model: params.model,
          });

          return {
            async *[Symbol.asyncIterator]() {
              for (const chunk of streamData) {
                yield chunk;
              }
            },
          };
        }

        return createMockMistralResponse(
          behavior.content || 'Mock response',
          behavior.responseOptions || {},
        );
      }),
    },
  };
}
